version: '3.4'

services:
  wguhelpdesk:
    image: wguhelpdesk
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 8080"]
    ports:
      - 8080:8080
      - 5678:5678
    environment:
      - FLASK_APP=wsgi.py
      #- FLASK_APP=backend/wsgi.py
  db:
    image: "postgres:12"
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
    pgdata:
